#ifndef _FUNCTION_CALL_VARIATIONS_ON_ONE_TYPE_AND_TEMP_VARIABLE_BY_COMPILER_
#define _FUNCTION_CALL_VARIATIONS_ON_ONE_TYPE_AND_TEMP_VARIABLE_BY_COMPILER_

void f(char);
void g(char&);
void h(const char&);

#endif
